### ISSUE TITLE
angular build error

### ISSUE THREAD

**Issue by massaroni** [bojidaryovchev/nest-angular#4]
First, thanks @bojidaryovchev for this project, this is really nice.

However, I'm going through the commands in the README, and I'm getting this error building the angular client.

I'm running node v10.3.0 and npm 6.1.0

$ npm run build:universal

> nest-angular@1.0.0 build:universal /.../nest-angular
> ng build --prod && ng run nest-angular:server

                                                                                   
Date: 2018-06-05T02:11:49.883Z
Hash: db74eca7defd6abb3323
Time: 10524ms
chunk {0} runtime.6afe30102d8fe7337431.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.67d1d24c839399719958.css (styles) 170 kB [initial] [rendered]
chunk {2} polyfills.4052eade0562922bb912.js (polyfills) 128 bytes [initial] [rendered]
chunk {3} main.967b3b53a13984a78c42.js (main) 128 bytes [initial] [rendered]

ERROR in node_modules/@types/ws/index.d.ts(179,24): error TS2694: Namespace '"net"' has no exported member 'AddressInfo'.
src/client/app/app.graphql.module.ts(46,57): error TS2345: Argument of type 'DocumentNode' is not assignable to parameter of type 'DocumentNode'.
  Types of property 'loc' are incompatible.
    Type 'Location' is not assignable to type 'Location'. Two different types with this name exist, but they are unrelated.
      Types of property 'startToken' are incompatible.
        Type 'Token' is not assignable to type 'Token'. Two different types with this name exist, but they are unrelated.
          Types of property 'prev' are incompatible.
            Type 'Token' is not assignable to type 'Token'. Two different types with this name exist, but they are unrelated.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nest-angular@1.0.0 build:universal: `ng build --prod && ng run nest-angular:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nest-angular@1.0.0 build:universal script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bojidaryovchev** [comment]
Thanks for reporting, I hadn't noticed it.. Anyway, I commented out the graphql module because it references the ws package types and theres an issue with those types.. If you want to have graphql support on the server and client, follow the instructions in the readme file which I shall now write

**Comment by massaroni** [comment]
Thanks, I can confirm it's now building successfully.
