### ISSUE TITLE
How do I run this on a server?

### ISSUE THREAD

**Issue by Faisalnwz01** [bojidaryovchev/nest-angular#6]
I am running `npm run build` with `NODE_ENV=production` to build out the production build. If I run the node `dist/server/main.js` express doesn't work. Is there any documentation around this?

p.s. 
If I run `node bin/server.bundle.js` I get an error that `throw new Error("[HMR] Hot Module Replacement is disabled.");`

**Comment by bojidaryovchev** [comment]
Could u explain further what exactly are you trying to do, like step by step?
The dist folder contains the angular builds, the server build is in the bin folder

**Comment by bojidaryovchev** [comment]
OK I saw what you mean by trying to deploy it to heroku.. I think its fixed now.. anyway keep in mind that currently the server modules depend on mongodb connection so unless provided an error will be thrown..

**Comment by Faisalnwz01** [comment]
@bojidaryovchev Yep that seemed like it did it. Thanks for the quick reply. 

Closing the issue!

**Comment by jamesliauw** [comment]
![image](https://user-images.githubusercontent.com/2033010/44615239-0cd2b200-a868-11e8-8cf3-711a2964dc04.png)

when i run node ./bin/server.bundle.js, but just console this message,  my question is:
How to visit? http://localhost:300?, but it not work.

**Comment by jamesliauw** [comment]
I mean in SSR mode, how to deploy and run my application?
